### ISSUE TITLE
Hobby list or location does not update after i manually set new location from map

### ISSUE THREAD

**Issue by MikkiYleva** [City-of-Helsinki/harrastuspassi-ui-ios#39]
After i manually pick new location from map the hobbylist keeps showing me hobbies from the previously picked location. If i refresh this does not help. After picking new locations manually the location does not really change and instead the map view is showing me the old location. If i want application to confirm new location settings i have to go to settings and enable "use my current location" and the disable it again. After i do this. the hobbylist gets updated and its showing me hobbies nearby selected location.

**Comment by Liikemies** [comment]
Today i was not able to reproduce this issue.
