### ISSUE TITLE
HobbyList scrolls endlessly with duplicate item

### ISSUE THREAD

**Issue by Nikokoli** [City-of-Helsinki/harrastuspassi-ui-ios#44]
Found this issue with iPhone 7 running iOS 14.2
Harrastuspassi app version was 1.6.1 located in Tampere

I found two ways to repro this issue:

A)

Open HobbyList view
Start scrolling down until listview's last item is met
Keep scrolling down. The list view starts to duplicate the last item ( For me it was Tuppikosken uimapaikka)

B) 
Open HobbyList view
Open Filter view
Select some category which doesn't have hobbies near your location. ( I selected ball games)
Apply filter
App gives me an empty list to indicate that there are no search results
Pull down to refresh the list view
Tuppikosken uimapaikka appears and starts duplicating

At first I thought this is about ListView component somehow duplicates the last item in the list, but then I tried to filter the results and accidentally hit the refresh and noticed that the same tuppikosken uimapaikka appeared over and over again. And it's not in ball game category

Expected result
The list view component should not duplicate the last item or show items from different category on refresh when initial search result is empty

https://user-images.githubusercontent.com/11889264/103886708-95c1af80-50ea-11eb-90c0-845eb351daf8.mov

**Comment by Liikemies** [comment]
I was able to repro this issue with both methods described ny @Nikokoli (A &B)

iPhone 11
Runnin iOs 14.4.2

Harrastuspassi version 1.6.1
